### PR TITLE
fix(otlp): surface transport errors at ERROR level

### LINKED ISSUE #3331: [Bug]: Improve context in BatchSpanProcessor/BatchLogProcessor error logs when otlp export fails
### What happened?

Currently, when `otlp` export fails due to transport errors, e.g. misconfigured endpoint, the error level logs are not helpful finding the root cause of the problem.

## Current Behavior
With a misconfigured endpoint (missing schema, e.g., `localhost:4317` instead of `http://localhost:4317`):

**Error-level log:**
```
2026-01-29T12:12:15.755056Z error opentelemetry_sdk
  name="BatchSpanProcessor.ExportError"
  error="Operation failed: status: 'Unknown error', self: \"transport error\""
```

**Debug-level log:**
```
2026-01-29T12:33:01.335273Z debug tonic::transport::channel::service::reconnect
  reconnect::poll_ready: ConnectError(ConnectError("invalid URL, scheme is missing"))
```

Looks like we lose the context when the original error gets wrapped into `OTelSdkError::InternalFailure` and the processors log it as a generic error without the original context.

I propose preserving the original error in `InternalFailure` in error messages. What do you all think?

### OpenTelemetry API Version (i.e version of `opentelemetry` crate)

main

### OpenTelemetry SDK Version (i.e version of `opentelemetry_sdk` crate)

main

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

See above.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by krisztianfekete**
Fixes #3331 

## Problem

When OTLP export fails because of a misconfigured endpoint (missing URL scheme, connection refused, wrong host), the ERROR log looks like this:

`error="Operation failed: TonicTracesClient export failed with gRPC code: Unknown"`

Which tells you nothing actionable. To find out what actually went wrong, e.g. that your URL is missing a scheme you currently have to enable DEBUG logging, where the real message finally shows up.

## After this change:

We have
`error="Operation failed: TonicTracesClient export failed with gRPC code: Unknown: transport error: invalid URI"`

Same for connect failures:

 `error="... gRPC code: Unavailable: transport error: tcp connect error: Connection refused (os error 111)"`

`tonic::Status::source()` already tells us whether the error came from the local transport stack (safe to show) or from the server (might echo auth tokens, per #3360), so we just append the source chain in the first case and keep the second case DEBUG-only. 

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by krisztianfekete** [comment]
The linter failure seems to be unrelated to my changes.

File: opentelemetry-otlp/src/exporter/http/mod.rs [hunk 1]
```diff
@@ -500,7 +500,7 @@ impl OtlpHttpClient {
                 url = request_uri.as_str(),
                 error = format!("{e}")
             );
-            HttpExportError::new(0, "HTTP export failed: network error".to_string())
+            HttpExportError::new(0, format!("HTTP export failed: network error: {e}"))
```
Comment (lalitb) [inline opentelemetry-otlp/src/exporter/http/mod.rs]: This line looks a bit risky to me. On the HTTP side, `e` can be a client error whose message includes the full URL, so this might end up surfacing secrets from the endpoint at ERROR level. Could we avoid returning the raw error text here, or at least sanitize it first?

Comment (krisztianfekete) [reply opentelemetry-otlp/src/exporter/http/mod.rs]: Makes sense, I reverted this, and kept it tonic-only.

**Comment by krisztianfekete** [comment]
@lalitb, can you please re-review once you have a chance? Thank you!

**Review by lalitb — APPROVED** [review]
LGTM. Nit to update the PR desc as it still mentions HTTP side.

**Comment by krisztianfekete** [comment]
Thanks @lalitb, just updated the description! I think it's ready to be merged.
