### PR TITLE
fix: return current context in on_end instead of causing panic

### LINKED ISSUE #2871: Trace SDK and Context access issue
Accessing current context on Span's `OnEnd` panics. `OnBegin` is fine, but OnBegin is given an explicit context, but OnEnd does not get any, so has to rely on current (which panics)

Related is the old spec issue: https://github.com/open-telemetry/opentelemetry-specification/issues/867

### PR DESCRIPTION
**Pull request by taisho6339**
Fixes #2871 

## Problem

Context::current() panicked with "RefCell already mutably borrowed" when called from SpanProcessor::on_end during span cleanup. Root cause: ContextGuard::drop held a mutable borrow while dropping the context, which triggered Span::drop → on_end → Context::current() → panic.

## Solution

Modified ContextGuard::drop to extract the context outside the borrow_mut() scope before dropping it:

```rust
impl Drop for ContextGuard {
    fn drop(&mut self) {
        let _to_drop = CURRENT_CONTEXT.with(|stack| {
            stack.borrow_mut().pop_id(id)  // Extract only
        }); // borrow_mut released here
        // Drop happens here - safe to call Context::current()
    }
}
```

## Changes

* opentelemetry: Modified ContextGuard::drop and ContextStack::pop_id, added documentation
* opentelemetry-sdk: Added SpanProcessor::on_end documentation with best practices

## Note

* Context::current() called during drop returns the parent context (documented behavior).
* Best practice: Extract context info in on_start and store as span attributes.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

File: opentelemetry-sdk/src/trace/span_processor.rs [hunk 1]
```diff
@@ -79,9 +79,43 @@ pub trait SpanProcessor: Send + Sync + std::fmt::Debug {
...
     fn on_start(&self, span: &mut Span, cx: &Context);
+
     /// `on_end` is called after a `Span` is ended (i.e., the end timestamp is
     /// already set). This method is called synchronously within the `Span::end`
     /// API, therefore it should not block or throw an exception.
+    ///
+    /// # Accessing Context
+    ///
+    /// If you need to access context information (such as baggage) in `on_end`,
+    /// note that calling [`Context::current()`] will return the **parent context**,
```
Comment (bantonsson) [inline opentelemetry-sdk/src/trace/span_processor.rs]: This is not necessarily true. You can call `Span.end()` with any `Context` set and `Context::current()` will get you what just happens to be there. Contexts can also be activated in whatever order you want and not necessarily in a hierarchy, so the `Context` that we switch back to in the `Drop` implementation of the `ContextGuard` can be completely unrelated to the `Context` that the `Span` is in. I would not trust anything from `Context::current()` in the `on_end` method.

File: opentelemetry/src/context.rs [hunk 2]
```diff
@@ -543,7 +561,7 @@ impl ContextStack {
     }
 
     #[inline(always)]
-    fn pop_id(&mut self, pos: u16) {
+    fn pop_id(&mut self, pos: u16) -> Option<Context> {
```
Comment (bantonsson) [inline opentelemetry/src/context.rs]: Returning the full `Option<Context>` seems to be expensive (at least on my MBP M4 Max) adding between `12%` and `20%` on context enter/exit benchmarks in `attach_context/...`. Would it be possible to try with a more specialized variant that only returns the `Span` if needed?

You could add a type alias along these lines.

```rust
#[cfg(not(feature = "tracing"))]
type OptionalReturn = Option<()>;
#[cfg(feature = "tracing")]
type OptionalReturn = Option<Arc<SynchronizedSpan>>;
```

And then do some optional processing in the code based on features.

Comment (taisho6339) [reply opentelemetry/src/context.rs]: Thanks for suggesting! If I understand correctly, it seems that the cloning cost is expensive. let me embrace your suggestions!

**Comment by bantonsson** [comment]
Thank you @taisho6339. The Benchmark numbers look way better now (actually resulting in some benchmarks running faster).

I don't see exactly these changes on my MBP M4 Max, but a degradation between 2 and 8 percent which is totally acceptable.

| name                                                          | baseDuration          | changesDuration     | difference |
|---------------------------------------------------------------|-----------------------|---------------------|------------|
| `context/has_active_span/in-cx/alt`                           | `8.4±0.06ns`          | `8.4±0.02ns`        | `0.0`      |
| `context/has_active_span/in-cx/spec`                          | **`4.2±0.17ns`**      | `4.4±0.16ns`        | `+4.0`     |
| `context/has_active_span/no-cx/alt`                           | `8.5±0.36ns`          | **`8.4±0.07ns`**    | `-0.99`    |
| `context/has_active_span/no-cx/spec`                          | **`4.4±0.19ns`**      | `4.7±0.24ns`        | `+7.0`     |
| `context/has_active_span/no-sdk/alt`                          | `8.4±0.06ns`          | `8.4±0.04ns`        | `0.0`      |
| `context/has_active_span/no-sdk/spec`                         | **`4.4±0.20ns`**      | `4.7±0.22ns`        | `+7.0`     |
| `context/is_recording/in-cx/alt`                              | `5.0±0.81ns`          | **`4.7±0.17ns`**    | `-6.5`     |
| `context/is_recording/in-cx/spec`                             | **`6.6±0.28ns`**      | `6.9±0.51ns`        | `+5.0`     |
| `context/is_recording/no-cx/alt`                              | `4.7±0.20ns`          | **`4.7±0.18ns`**    | `-0.99`    |
| `context/is_recording/no-cx/spec`                             | **`6.6±0.29ns`**      | `7.2±0.18ns`        | `+9.0`     |
| `context/is_recording/no-sdk/alt`                             | `4.7±0.13ns`          | `4.7±0.12ns`        | `0.0`      |
| `context/is_recording/no-sdk/spec`                            | **`6.6±0.21ns`**      | `7.2±0.56ns`        | `+10`      |
| `context/is_sampled/in-cx/alt`                                | `8.7±0.03ns`          | `8.7±0.03ns`        | `0.0`      |
| `context/is_sampled/in-cx/spec`                               | **`4.4±0.12ns`**      | `4.7±0.22ns`        | `+6.0`     |
| `context/is_sampled/no-cx/alt`                                | `8.7±0.03ns`          | `8.7±0.03ns`        | `0.0`      |
| `context/is_sampled/no-cx/spec`                               | **`4.7±0.16ns`**      | `5.0±0.26ns`        | `+7.0`     |
| `context/is_sampled/no-sdk/alt`                               | `8.7±0.10ns`          | `8.7±0.03ns`        | `0.0`      |
| `context/is_sampled/no-sdk/spec`                              | **`4.7±0.18ns`**      | `5.0±0.25ns`        | `+7.0`     |
| `context_attach/nested_cx/empty_cx`                           | `46.8±1.12ns`         | **`37.0±1.13ns`**   | `-21`      |
| `context_attach/nested_cx/single_value_cx`                    | `48.2±1.16ns`         | **`43.0±0.92ns`**   | `-11`      |
| `context_attach/nested_cx/span_cx`                            | `48.2±1.30ns`         | **`43.6±0.96ns`**   | `-9.1`     |
| `context_attach/out_of_order_cx_drop/empty_cx`                | `41.4±0.93ns`         | **`36.9±0.82ns`**   | `-11`      |
| `context_attach/out_of_order_cx_drop/single_value_cx`         | `42.4±1.78ns`         | **`41.2±1.12ns`**   | `-2.9`     |
| `context_attach/out_of_order_cx_drop/span_cx`                 | `42.7±1.50ns`         | **`41.4±1.08ns`**   | `-2.9`     |
| `context_attach/single_cx/empty_cx`                           | `24.2±0.44ns`         | **`19.5±0.87ns`**   | `-19`      |
| `context_attach/single_cx/single_value_cx`                    | `23.6±0.81ns`         | **`21.8±0.60ns`**   | `-7.4`     |
| `context_attach/single_cx/span_cx`                            | `23.6±0.93ns`         | **`22.4±0.36ns`**   | `-5.7`     |
| `telemetry_suppression/enter_telemetry_suppressed_scope`      | `26.5±0.35ns`         | **`23.2±0.35ns`**   | `-12`      |
| `telemetry_suppression/is_current_telemetry_suppressed_false` | `0.9±0.04ns`          | **`0.8±0.02ns`**    | `-0.99`    |
| `telemetry_suppression/is_current_telemetry_suppressed_true`  | `0.9±0.05ns`          | **`0.8±0.02ns`**    | `-2.0`     |
| `telemetry_suppression/normal_attach`                         | `29.9±0.83ns`         | **`26.8±1.06ns`**   | `-9.9`     |

File: opentelemetry-sdk/src/trace/mod.rs [hunk 3]
```diff
@@ -137,10 +137,32 @@ mod tests {
...
 
-        fn on_end(&self, _span: SpanData) {
-            // TODO: Accessing Context::current() will panic today and hence commented out.
+        fn on_end(&self, span: SpanData) {
+            // Fixed: Context::current() no longer panics from Drop
             // See https://github.com/open-telemetry/opentelemetry-rust/issues/2871
-            // let _c = Context::current();
+            let current_cx = Context::current();
+
+            // IMPORTANT NOTE: The context returned here is the PARENT context,
```
Comment (bantonsson) [inline opentelemetry-sdk/src/trace/mod.rs]: This comment is still a bit missleading.

Comment (taisho6339) [reply opentelemetry-sdk/src/trace/mod.rs]: Thanks. Fixed 
https://github.com/open-telemetry/opentelemetry-rust/pull/3262/commits/6c6a35b12cd8a840c121679842a0c3cfba578af5

**Comment by bantonsson** [comment]
Could you please review when you have the time @cijothomas

**Comment by cijothomas** [comment]
@taisho6339 Once again, apologies for not back to this sooner.! Could you resolve the conflicts and we can get it merged today! Thanks for waiting patiently!
