### PR TITLE
fix: handle shutdown in logs exporter

### LINKED ISSUE #2777: Handle shutdown in OTLP/gRPC
tonic does not handle shutdown properly today. The gRPC client is not dropped during shutdown. 

See discussion here: https://github.com/open-telemetry/opentelemetry-rust/pull/2764#discussion_r1986133497

### PR DESCRIPTION
**Pull request by stefanobaghino**
Fixes #2777

## Changes

This follows the approach suggested [here](https://github.com/open-telemetry/opentelemetry-rust/issues/2777#issuecomment-3566350234) by @scottgerring:

> The issue is in `TonicLogsClient` which uses `tokio::sync::Mutex` (async) but the `LogExporter::shutdown_with_timeout()` trait method is synchronous. This prevents calling `.lock().await`, so the current implementation has a TODO and just returns `Ok()` without actually shutting down the gRPC client.
> 
> Comparing shutdown on `TonicMetricsClient` , and in particular the type of the mutex used for the inner client and locked in the shutdown, seems to show a workable pattern.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

File: opentelemetry-otlp/src/exporter/tonic/metrics.rs [hunk 1]
```diff
@@ -93,7 +93,7 @@ impl MetricsClient for TonicMetricsClient {
                             Ok((inner.client.clone(), m, e))
                         }
                         None => Err(tonic::Status::failed_precondition(
-                            "exporter is already shut down",
+                            "metrics exporter is already shut down",
```
Comment (scottgerring) [inline opentelemetry-otlp/src/exporter/tonic/metrics.rs:96]: I think this is helpful; I don't think the user would necessarily see which failed otherwise

**Review by scottgerring — APPROVED** [review]
Thanks! LGTM

File: opentelemetry-otlp/CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,9 @@
 
 - Add partial success response handling for OTLP exporters (traces, metrics, logs) per OTLP spec. Exporters now log warnings when the server returns partial success responses with rejected items and error messages. [#865](https://github.com/open-telemetry/opentelemetry-rust/issues/865)
 - Refactor `internal-logs` feature in `opentelemetry-otlp` to reduce unnecessary dependencies[3191](https://github.com/open-telemetry/opentelemetry-rust/pull/3192)
+- Fixed
+  [#2777](https://github.com/open-telemetry/opentelemetry-rust/issues/2777)
+  to properly handle `shutdown_with_timeout()` when using `tonic`.
```
Comment (scottgerring) [inline opentelemetry-otlp/CHANGELOG.md]: nit: No need to wrap, and we can reference the feature name `grpc-tonic` 

```suggestion
- Fixed [#2777](https://github.com/open-telemetry/opentelemetry rust/issues/2777)  to properly handle `shutdown_with_timeout()` when using `grpc-tonic`.
```

**Comment by scottgerring** [comment]
@stefanobaghino that was a quick turnaround :D

File: opentelemetry-otlp/src/exporter/tonic/logs.rs [hunk 3]
```diff
@@ -5,9 +5,8 @@ use opentelemetry_proto::tonic::collector::logs::v1::{
 };
 use opentelemetry_sdk::error::{OTelSdkError, OTelSdkResult};
 use opentelemetry_sdk::logs::{LogBatch, LogExporter};
-use std::sync::Arc;
+use std::sync::{Arc, Mutex};
```
Comment (cijothomas) [inline opentelemetry-otlp/src/exporter/tonic/logs.rs:8]: are there any repercussions of moving to std Mutex instead of tokio one inside the async export call?

Comment (scottgerring) [reply opentelemetry-otlp/src/exporter/tonic/logs.rs:8]: I think it's fine, and its the same pattern used in `TonicsMetricsClient` for the last couple years, which as far as I can tell we've not had problems with ([linky to blame](https://github.com/open-telemetry/opentelemetry-rust/blame/df412fecf79350f5ccc303c494767d826ed8c979/opentelemetry-otlp/src/exporter/tonic/metrics.rs#L19)).

In the export, we hold the lock only so long as to clone the client and call the interceptor - and significantly, not across any await points, which is the main contra-indicator for std mutexes:

```rust
                let (mut client, metadata, extensions) = self
                    .inner
                    .lock()
                    .map_err(|e| tonic::Status::internal(format!("Failed to acquire lock: {e:?}")))
                    .and_then(|mut inner| match &mut *inner {
Some(inner) => {
let (m, e, _) = inner
.interceptor
.call(Request::new(()))
.map_err(|e| {
// Convert interceptor errors to tonic::Status for retry classification
tonic::Status::internal(format!("interceptor error: {e:?}"))
})? // lock released
```

I _think_ if you called `shutdown_with_timeout` on a single-threaded tokio runtime while the runtime is still trying to do an export, _and_ the export was at that exact moment in the code I highlighted above, _then_ you could potentially deadlock it, but this relies on amazing timing, and I think we already warn against doing exactly this:

https://github.com/open-telemetry/opentelemetry-rust/blob/df412fecf79350f5ccc303c494767d826ed8c979/opentelemetry-sdk/src/logs/batch_log_processor.rs#L99-L102

I note there are some other suggestions (e.g. spawning a thread) to do this particular thing in the linked issue, but this feels a bit overwrought. 

What are you thinking @cijothomas ?

**Comment by stefanobaghino** [comment]
I'd be happy to take any additional feedback on this. If this is not a satisfactory approach, I also have nothing against closing this. Please let me know how to progress. Thanks.

File: opentelemetry-otlp/src/exporter/tonic/logs.rs (hunk 3 above)
Comment (cijothomas) [reply opentelemetry-otlp/src/exporter/tonic/logs.rs:8]: okay given we drop the lock guard before the async export call, this should be fine.

If we do something for
https://github.com/open-telemetry/opentelemetry-rust/issues/2881 we should make sure its not going to cause any issues.
