### PR TITLE
Fix aggregation for Gauge

### LINKED ISSUE #1975: [Bug]: Metrics - Gauge stops reporting after being recorded
### What happened?

In our application we periodically record a Gauge<u64> every 60 seconds.  We use the `opentelemetry-prometheus` exporter and host a metrics endpoint where we scrape our prometheus metrics from OpenTelemetry.

We have other metrics (Histogram, Counter) that always show up on our prometheus metrics endpoint.  However for gauges, if more than a second goes by between calls to `record` for the gauge - the gauge stops being exposed on our prometheus endpoint, the metric value, description, and type all dissapear.  It then returns when we record the Gauge. 

We tried switching to the `opentelemetry_stdout` library instead of prometheus and saw the same behavior - the gauge would disappear from the metrics exporter within a second or two after it was last recorded, and then reappear when we recorded a new value.

For context, our prometheus instance scrapes our application periodically every 5s.  So with the Gauge intermittently deregistering itself, we have a race condition where we may not be recording the Gauge value.

Is this known, intended behavior? I wasn't able to find a reference to this in the [opentelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge) on gauges.  If it is intended - is there any way to customize the Gauge expiration so we can have it persist in the metrics provider context for longer?

### API Version

0.24

### SDK Version

0.24

### What Exporter(s) are you seeing the problem on?

Prometheus

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by utpilla**
Fixes #1975 

## Changes
- Added dedicated collect handling logic for Delta and Cumulative temporality for Gauge
- Added a test to ensure that asynchronous instruments with Cumulative temporality keep reporting the last recorded measurement if there was no new measurement made from the last collect

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 1]
```diff
@@ -1404,6 +1400,133 @@ mod tests {
...
     }
 
+    #[tokio::test(flavor = "multi_thread", worker_threads = 1)]
+    async fn asynchronous_instruments_cumulative_with_gap_in_measurements() {
+        // Run this test with stdout enabled to see output.
+        // cargo test asynchronous_instruments_cumulative_with_gap_in_measurements --features=testing -- --nocapture
+
+        asynchronous_instruments_cumulative_with_gap_in_measurements_helper("counter");
+        asynchronous_instruments_cumulative_with_gap_in_measurements_helper("updown_counter");
+        asynchronous_instruments_cumulative_with_gap_in_measurements_helper("gauge");
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/mod.rs:1410]: The test for `Gauge` would fail without this fix.

File: opentelemetry-sdk/src/metrics/internal/aggregate.rs [hunk 2]
```diff
@@ -113,6 +113,7 @@ impl<T: Number<T>> AggregateBuilder<T> {
         // a last-value aggregate.
         let lv_filter = Arc::new(LastValue::new());
         let lv_agg = Arc::clone(&lv_filter);
+        let t = self.temporality;
```
Comment (lalitb) [inline opentelemetry-sdk/src/metrics/internal/aggregate.rs:116]: nit - should we update the function comment, as the temporality is no longer ignored now?

File: opentelemetry-sdk/src/metrics/internal/aggregate.rs [hunk 3]
```diff
@@ -127,7 +128,12 @@ impl<T: Number<T>> AggregateBuilder<T> {
                 };
                 let g = g.unwrap_or_else(|| new_agg.as_mut().expect("present if g is none"));
 
-                lv_agg.compute_aggregation(&mut g.data_points);
+                match t {
+                    Some(Temporality::Delta) => {
+                        lv_agg.compute_aggregation_delta(&mut g.data_points)
```
Comment (lalitb) [inline opentelemetry-sdk/src/metrics/internal/aggregate.rs:133]: nit - how about naming these methods delta() and cumulative(), to be consistent with naming in other aggregates?

**Review by lalitb — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]
LGTM, please add a changelog entry for the bugfix

File: opentelemetry-sdk/src/metrics/internal/aggregate.rs (hunk 3 above)
Comment (utpilla) [reply opentelemetry-sdk/src/metrics/internal/aggregate.rs:133]: The code setup for `last_value` is not consistent with other aggregates. `delta` and `cumulative` of other aggregates return a tuple `(usize, Option<Box<dyn Aggregation>>)` whereas the `compute_aggregation` methods of `last_value` do not return anything.

I would like to make the code setup for `Gauge` consistent with other aggregates in a different PR. Is it okay to fix it then?

File: opentelemetry-sdk/src/metrics/internal/aggregate.rs (hunk 2 above)
Comment (utpilla) [reply opentelemetry-sdk/src/metrics/internal/aggregate.rs:112]: Thanks! Updated.
