### PR TITLE
fix(proto): preserve InstrumentationScope version and attributes

### LINKED ISSUE #3276: [Bug]: opentelemetry-proto discards InstrumentationScope attributes for logs
### What happened?

When using the `SdkLoggerProvider::logger_with_scope` API to use an `InstrumentationScope` with attributes, these attributes are discarded when building the log export body via `OtlpHttpClient::build_logs_export_body`

More precisely, [`group_logs_by_resource_and_scope`](opentelemetry_proto::transform::logs::tonic::group_logs_by_resource_and_scope) call of [`opentelemetry_proto::transform::common::tonic::InstrumentationScope::from`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/src/transform/common.rs#L45) is called with `Some` in [the second position of the tuple](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/src/transform/logs.rs#L200), [which causes](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/src/transform/common.rs#L58) InstrumentationScope::from to use an [empty vector](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/src/transform/common.rs#L62) for it's attributes.

This differs for example from the behaviour of `group_spans_by_resource_and_scope` which [uses `None`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-proto/src/transform/trace.rs#L194) when creating the `InstrumentationScope`, causing scope attributes to be retained as expected.

### OpenTelemetry API Version (i.e version of `opentelemetry` crate)

0.31.0

### OpenTelemetry SDK Version (i.e version of `opentelemetry_sdk` crate)

0.31.0

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell

```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by djvcom**
## Summary

When logs have a target set, the `InstrumentationScope`'s version and attributes were being discarded during OTLP export. The target parameter now correctly overrides only the scope name, preserving other metadata.

- Fix `From` implementations for `InstrumentationScope` to preserve version and attributes when target is provided
- Add unit tests for the `From` implementations
- Add integration test demonstrating the fix with `group_logs_by_resource_and_scope`

## Context

This behaviour was introduced in PR #1869 to avoid exporting the appender crate's version when the scope name was overridden by target. However, PRs #2735 and #2796 subsequently changed both appenders to use empty scopes, so this concern no longer applies. Additionally, users who explicitly create scopes via `logger_with_scope()` would reasonably expect their metadata to be preserved.

## Test plan

- [x] Unit tests for both owned and reference `From` implementations
- [x] Integration test for `group_logs_by_resource_and_scope` with target set
- [x] `cargo test -p opentelemetry-proto --all-features --lib` passes
- [x] `cargo clippy -p opentelemetry-proto --all-features -- -Dwarnings` passes

Fixes #3276

### CODE REVIEW

**Comment by djvcom** [comment]
Hi there, first time contributing here so please let me know if I need to change anything (or if I'm not allowed to contribute etc). Sorry if I've done anything wrong!

File: opentelemetry-proto/src/transform/common.rs [hunk 1]
```diff
@@ -55,20 +55,11 @@ pub mod tonic {
...
-                    ..Default::default()
-                }
-            } else {
-                InstrumentationScope {
-                    name: library.name().to_owned(),
-                    version: library.version().map(ToOwned::to_owned).unwrap_or_default(),
-                    attributes: Attributes::from(library.attributes().cloned()).0,
-                    ..Default::default()
-                }
+            InstrumentationScope {
```
Comment (cijothomas) [inline opentelemetry-proto/src/transform/common.rs:58]: not introduced by this PR, but this area is quite expensive due to copy/allocation etc. https://github.com/open-telemetry/opentelemetry-rust/pull/3307/ exposes the cost of this conversion!

Just FYI, nothing for this PR. The whole idea of target and instrumentation scope needs to be revisited to improve the performance.

Comment (cijothomas) [reply opentelemetry-proto/src/transform/common.rs:58]: @djvcom Out of curiosity, can you elaborate on how did you hit this issue yourselves? The log appenders shipped in this repo always set a target and the scope attributes are empty, so this should have caused no issue. So wondering how did you hit the issue here. This is merely to help us understand the space better which will help future perf improvements!

Comment (djvcom) [reply opentelemetry-proto/src/transform/common.rs:58]: I was creating a scope manually as well (i've been building a little rust project to help me test collector configurations are valid). I doubt that most users would ever encounter it, and it was only because I was looking to verify and assert against resource and scope attrs that I noticed it, and the issue raised. All of my use cases I use the tracing appender, so I won't even benefit from this change in my day to day, but still thought it worth addressing.

**Comment by scottgerring** [comment]
> @scottgerring yep, I did look at his work as a reference point for getting started on it. Do you think this is still needed? Happy to make any changes as required or close if not? I'd forgotten about it 😅

As there's a couple folks who've hit it now and this looks like a clean change to me I reckon we should merge it. @cijothomas wdyt?

**Review by scottgerring — APPROVED** [review]

**Comment by djvcom** [comment]
Hi @cijothomas, I'm wondering whether there's anything I can do on this one to get it merged? Or would you prefer I close the PR? (Just trying to wrap up some loose ends).

**Comment by djvcom** [comment]
Hi @scottgerring, I'm not sure whether you might be able to help get this one merged (or let me know if I should close it)? Sorry to chase!

**Comment by scottgerring** [comment]
> Hi @scottgerring, I'm not sure whether you might be able to help get this one merged (or let me know if I should close it)? Sorry to chase!

Hey @djvcom , @cijothomas and @lalitb should be back on deck this week and hold the merge keys; pinging for visibility

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
> > Hi @scottgerring, I'm not sure whether you might be able to help get this one merged (or let me know if I should close it)? Sorry to chase!
> 
> Hey @djvcom , @cijothomas and @lalitb should be back on deck this week and hold the merge keys; pinging for visibility

Added to merge-queue. There are some Github issues going on right now, so this will be merged as soon as they are resolved.
