### PR TITLE
fix(otlp): error on HTTPS endpoint when TLS feature is not enabled

### LINKED ISSUE #3182: [Bug]: Without the `tls` feature, the Tonic exporter sends unencrypted data to a HTTPS endpoint
### What happened?

When using the default Cargo features for the `opentelemetry-otlp` crate, the `tls` feature is off by default. Enabling the `grpc-tonic` feature does *not* enable TLS.

With the environment variable `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://otlp.arize.com/v1` set, and using an exporter built with:
```rust
opentelemetry_otlp::SpanExporter::builder()
.with_tonic()
.build()
```

I observed plain HTTP (non-TLS) traffic being sent to otlp.arize.com (using Wireshark), even though my endpoint url explicitly mentions `https` Since the remote server is expecting TLS on port 443, the `opentelemetry-otlp` report tries to parse the server TLS error as plain HTTP, resulting in a confusing error message:

```
ERROR opentelemetry_sdk:  name="BatchSpanProcessor.ExportError" error="Operation failed: status: Unknown, message: \"transport error\", details: [], metadata: MetadataMap { headers: {} }"
```

I would expect that trying to using a `https` endpoint without the `tls` feature enabled produces an error, rather than silently attempting to use a non-encrypted connection on port 443.

### OpenTelemetry API Version (i.e version of `opentelemetry` crate)

v0.30.0

### OpenTelemetry SDK Version (i.e version of `opentelemetry_sdk` crate)

v0.30.0

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell

```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Summary

Closes #3182

When a user configures an `https://` endpoint (via environment variable or programmatically) but no TLS feature (`tls-ring` or `tls-aws-lc`) is enabled on `opentelemetry-otlp`, the tonic exporter silently sends unencrypted traffic over port 443. The remote server expects TLS, so the connection fails with a confusing transport error:

```
ERROR opentelemetry_sdk: name="BatchSpanProcessor.ExportError" error="Operation failed: status: Unknown, message: \"transport error\", ..."
```

This PR adds two behaviors to `build_channel()` in the tonic exporter:

- **No TLS feature compiled in + `https://` endpoint**: Returns `ExporterBuildError::InvalidConfig` with a clear error message telling the user to enable `tls-ring` or `tls-aws-lc`.
- **TLS feature enabled + `https://` endpoint + no explicit `tls_config`**: Auto-applies `ClientTlsConfig::new()` so TLS works out of the box, matching standard HTTP client behavior (e.g., reqwest automatically uses TLS for `https://` URLs). The explicit `.with_tls_config()` API remains available for custom TLS settings (custom CAs, client certs, etc.).

Scheme detection uses `http::Uri` parsing rather than string matching, so it correctly handles case-insensitive schemes (e.g., `HTTPS://my-endpoint`). The URL format is validated first via `Channel::from_shared()`, so invalid URLs get a proper error before the scheme check.

Plain `http://` endpoints are unaffected.

## Test plan

- [x] Added `test_https_endpoint_errors_without_tls_feature` — verifies `ExporterBuildError::InvalidConfig` is returned when TLS features are disabled and an `https://` endpoint is used
- [x] Added `test_https_endpoint_succeeds_with_tls_feature` — verifies auto-TLS configuration works when TLS features are enabled
- [x] Added `test_http_endpoint_succeeds_without_tls_feature` — verifies `http://` endpoints continue to work regardless of TLS feature state
- [x] Full test suite passes with `--features grpc-tonic` (no TLS) — 69 tests + 13 doc-tests
- [x] Full test suite passes with `--features grpc-tonic,tls-ring` (TLS enabled) — 69 tests + 13 doc-tests

### CODE REVIEW

File: opentelemetry-otlp/src/exporter/tonic/mod.rs [hunk 1]
```diff
@@ -236,6 +236,20 @@ impl TonicExporterBuilder {
...
+                name: "endpoint".to_string(),
+                reason: format!(
+                    "endpoint '{}' uses HTTPS but no TLS feature is enabled; \
+                     enable one of the `tls-ring` or `tls-aws-lc` features on `opentelemetry-otlp`",
+                    endpoint_clone
+                ),
+            });
+        }
+
         let endpoint = Channel::from_shared(endpoint)
```
Comment (scottgerring) [inline opentelemetry-otlp/src/exporter/tonic/mod.rs]: I think we can likely get the scheme off of the Uri on the endpoint, which would let us handle cases where users type in e.g. `HTTPS://my-endpoint` rather than relying on a string match

Comment (scottgerring) [reply opentelemetry-otlp/src/exporter/tonic/mod.rs]: I think this improves the error priority too - first validate URL format, then validate scheme

**Review by scottgerring — DISMISSED** [review]
Hey @bryantbiggs , thanks for this - it's something we definitely want to clean up! 
Minor feedback, but I think this is the right approach.
Could you also add a changelog entry to opentelemetry-otlp/changelog please?

File: opentelemetry-otlp/src/exporter/tonic/mod.rs (hunk 1 above)
Comment (bryantbiggs) [reply opentelemetry-otlp/src/exporter/tonic/mod.rs]: great point, updated!

Comment (bryantbiggs) [reply opentelemetry-otlp/src/exporter/tonic/mod.rs]: Updated - now using `http::Uri` to parse the endpoint and check the scheme via `uri.scheme() == Some(&http::uri::Scheme::HTTPS)`, which handles case-insensitive schemes like `HTTPS://`. Also moved the check after `Channel::from_shared()` so invalid URLs get a format error before the scheme validation.

File: opentelemetry-otlp/src/exporter/tonic/mod.rs [hunk 2]
```diff
@@ -238,13 +238,33 @@ impl TonicExporterBuilder {
 
         let endpoint = Channel::from_shared(endpoint)
             .map_err(|op| ExporterBuildError::InvalidUri(endpoint_clone.clone(), op.to_string()))?;
+
+        let is_https = http::Uri::from_str(&endpoint_clone)
```
Comment (scottgerring) [inline opentelemetry-otlp/src/exporter/tonic/mod.rs]: I think you can use the URI that's already parsed by the endpoint - something like this:

```rust
let is_https = endpoint
    .uri()
    .scheme()
    .is_some_and(|s| *s == http::uri::Scheme::HTTPS);
```

Comment (bryantbiggs) [reply opentelemetry-otlp/src/exporter/tonic/mod.rs]: Updated - now using `endpoint.uri().scheme().is_some_and(|s| *s == http::uri::Scheme::HTTPS)` to avoid the redundant parse. Also added the changelog entry.

File: opentelemetry-otlp/CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,9 @@
 
 ## vNext
 
+- Error when `https://` endpoint is configured but no TLS feature (`tls-ring` or `tls-aws-lc`) is enabled,
```
Comment (cijothomas) [inline opentelemetry-otlp/CHANGELOG.md]: lets be bit more detailed.
Make it obvious this is for all signals.
The error is from otlp exporter's build method.

Comment (cijothomas) [reply opentelemetry-otlp/CHANGELOG.md]: also if this is gRPC/tonic only, not http

**Review by cijothomas — COMMENTED** [review]
Looks good, waiting to resolve small suggestion about improved changelog wording before formal approval and merge.

File: opentelemetry-otlp/CHANGELOG.md (hunk 3 above)
Comment (bryantbiggs) [reply opentelemetry-otlp/CHANGELOG.md]: Updated the changelog entry to be more specific - clarifies this applies to the gRPC/tonic exporter's build method, affects all signals (traces, metrics, logs), and describes both behaviors (error without TLS feature, auto-apply default TLS config with TLS feature).

Comment (cijothomas) [reply opentelemetry-otlp/CHANGELOG.md]: looks good.
