### PR TITLE
fix: Change logger scope in log appender

### LINKED ISSUE #2747: Fix logger scope in log-appender
https://github.com/open-telemetry/opentelemetry-rust/pull/2735#pullrequestreview-2655144624

### PR DESCRIPTION
**Pull request by gruebel**
Fixes #2747 

## Changes

- I was not sure what exactly is the desired state for
https://github.com/open-telemetry/opentelemetry-rust/blob/1ddecb04d9f19dafab682be42c5a2579a8c8182d/opentelemetry-proto/src/transform/common.rs#L57
set all the values to empty strings/vec, if target is `None`?

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

File: opentelemetry-appender-tracing/src/layer.rs [hunk 1]
```diff
@@ -173,8 +173,7 @@ where
 
         let mut log_record = self.logger.create_log_record();
 
-        // TODO: Fix heap allocation
-        log_record.set_target(target.to_string());
+        log_record.set_target(target);
```
Comment (cijothomas) [inline opentelemetry-appender-tracing/src/layer.rs:176]: oh wait.. this works now?

Comment (cijothomas) [reply opentelemetry-appender-tracing/src/layer.rs:176]: @utpilla helped me understand better. We were unnecessarily copying the target before!

@gruebel Please do this change in a separate PR, with a before/after benchmark - it should show measurable improvement.

**Comment by cijothomas** [comment]
> Fixes #2747
> 
> ## Changes
> * I was not sure what exactly is the desired state for
>   https://github.com/open-telemetry/opentelemetry-rust/blob/1ddecb04d9f19dafab682be42c5a2579a8c8182d/opentelemetry-proto/src/transform/common.rs#L57
>   
>   set all the values to empty strings/vec, if target is `None`?


If target is None, then get everything from InstrumentationScope itself. If target is there, then it should be used for name/ver/schema_url. But we should still copy the Attributes from Scope. (This requires some more investigation, so we can tackle it later)

**Review by cijothomas — APPROVED** [review]
