### PR TITLE
fix(doc): update feature flag lists

### LINKED ISSUE #1464: [Bug]: cargo package features are ill documented
### What happened?

I went to install opentelemetry_sdk and saw that there are several flags. I went to look into what they are and I couldn't find any relevant documentation that covered them.

I looked in the following locations:
- https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry (readme)
- https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/Cargo.toml#L34
- https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-sdk (readme)
- https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/Cargo.toml#L46 

### API Version

0.21.0

### SDK Version

0.21.2

### What Exporters are you seeing the problem on?

N/A

### Relevant log output

```shell
cargo add --package $MYTHING opentelemetry
    Updating crates.io index
      Adding opentelemetry v0.21.0 to dependencies.
             Features:
             + pin-project-lite
             + trace
             - logs
             - logs_level_enabled
             - metrics
             - testing

cargo add --package $MYTHING opentelemetry_sdk
    Updating crates.io index
      Adding opentelemetry_sdk v0.21.2 to dependencies.
             Features:
             + async-trait
             + crossbeam-channel
             + percent-encoding
             + rand
             + trace
             - async-std
             - glob
             - http
             - jaeger_remote_sampler
             - logs
             - logs_level_enabled
             - metrics
             - opentelemetry-http
             - rt-async-std
             - rt-tokio
             - rt-tokio-current-thread
             - serde
             - serde_json
             - testing
             - tokio
             - tokio-stream
             - url
    Updating crates.io index
```

### PR DESCRIPTION
**Pull request by TommyCpp**
Fixes #1464 
Design discussion issue (if applicable) #

## Changes
- Update feature flag lists 

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

File: opentelemetry-sdk/src/lib.rs [hunk 1]
```diff
@@ -77,10 +77,19 @@
 //!
 //! ## Crate Feature Flags
 //!
-//! The following core crate feature flags are available:
+//! The following feature flags can used to control the telemetry pillars to use:
```
Comment (cijothomas) [inline opentelemetry-sdk/src/lib.rs:80]:
```suggestion
//! The following feature flags can used to control the telemetry signals to use:
```

File: opentelemetry/src/lib.rs [hunk 2]
```diff
@@ -96,6 +96,13 @@
 //! * `metrics`: Includes the unstable metrics API.
 //! * `logs`: Includes the logs bridge API.
 //!
+//! The following feature flags provides additional configuration for `logs`:
+//! * `logs_level_enabled`: Allow users to control the log level
+//!
+//! The following feature flags enables unstable APIs, those APIs are subject to changes without a major version bump,
```
Comment (cijothomas) [inline opentelemetry/src/lib.rs:102]: one caveat here is -- it may give the impression that the rest of the APIs are stable.. May not be any real issue, but just called out as I found it potentially misleading...

**Review by cijothomas — APPROVED** [review]

File: opentelemetry/src/lib.rs (hunk 2 above)
Comment (TommyCpp) [reply opentelemetry/src/lib.rs:102]: True. I will remove it for now

File: opentelemetry-otlp/src/lib.rs [hunk 3]
```diff
@@ -80,6 +80,38 @@
 //! [`tokio`]: https://tokio.rs
 //! [`async-std`]: https://async.rs
 //!
+//! # Feature Flags
+//! The following feature flags can enable exporters for different telemetry pillars:
```
[the remark this answers is not in the document]
Comment (TommyCpp) [reply opentelemetry-otlp/src/lib.rs:84]: Ahhhh I know there was a better word. Just couldn't remember it last night

**Comment by hdost** [comment]
Sorry to come late on this but i thought the reason we disabled the default flags was to make it easier for people to not use sys-openssl.

**Comment by hdost** [comment]
@TommyCpp @jtescher ?

**Comment by TommyCpp** [comment]
> Sorry to come late on this but i thought the reason we disabled the default flags was to make it easier for people to not use sys-openssl.

Sorry missed this. The reason I removed all configuration from crates is because cargo is warning about it. We can disable default features on workspace
