### PR TITLE
fix: Cardinality overflow to use bool value instead of string

### LINKED ISSUE #2878: [Bug]: Cardinality overflow metric should use a boolean value rather than a string
### What happened?

I'd say this is a pretty minor issue, but we did encounter it when looking specifically for this metric value so maybe it will help someone and maybe it should get fixed before a 1.x.

When hitting the cardinality limit for metrics export, the library correctly produces a _string value_ attribute `otel.metric.overflow` on the metrics instrument that has an overflow.  However [the OTel specification](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#overflow-attribute) indicates this should be a _boolean value_.  

I think the fix is to just remove the quotes, e.g. `"true"` => `true`:

https://github.com/open-telemetry/opentelemetry-rust/blob/b2de6cc5a3dc271fffee45f050e894fba57508ba/opentelemetry-sdk/src/metrics/internal/mod.rs#L27

This is probably not an issue post v0.28 since there is no longer a cardinality limit in place!  But probably worth noting as limits with configuration support are coming back in soon.

### OpenTelemetry API Version (i.e version of `opentelemetry` crate)

0.24.0

### OpenTelemetry SDK Version (i.e version of `opentelemetry_sdk` crate)

0.24.1

### What Exporter(s) are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by cijothomas**
Fixes #2878

### CODE REVIEW

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 1]
```diff
@@ -2838,6 +2833,16 @@ mod tests {
         })
     }
 
+    fn find_overflow_sum_datapoint<'a, T>(
+        data_points: &'a [SumDataPoint<T>],
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/mod.rs:2837]: There is a lint error asking to remove lifetime annotations here.
