### PR TITLE
fix: Allow Histograms with no buckets

### LINKED ISSUE #2354: It should be possible to export Histograms with no bucket information
https://github.com/open-telemetry/opentelemetry-rust/pull/2351#discussion_r1859581855 if user chose empty vec!.

### PR DESCRIPTION
**Pull request by cijothomas**
Fixes #2354

### CODE REVIEW

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 1]
```diff
@@ -2161,6 +2169,58 @@ mod tests {
...
+        // find and validate key1=value1 datapoint
+        let data_point =
+            find_histogram_datapoint_with_key_value(&histogram_data.data_points, "key1", "value1")
+                .expect("datapoint with key1=value1 expected");
+
+        assert_eq!(data_point.count, 5);
+        assert_eq!(data_point.sum, 15);
+
+        println!("bounds: {:?}", data_point.bounds);
+        println!("bucket_counts: {:?}", data_point.bucket_counts);
```
Comment (bantonsson) [inline opentelemetry-sdk/src/metrics/mod.rs:2219]: I'm wondering if tests should use the `otel_info!` macro instead?

**Review by bantonsson — APPROVED** [review]

File: opentelemetry-sdk/src/metrics/mod.rs (hunk 1 above)
Comment (cijothomas) [reply opentelemetry-sdk/src/metrics/mod.rs:2219]: Thanks! This was a leftover while I was authoring this ! Will remove it.
