### PR TITLE
Bugfix - add validation for custom buckets provided for Histograms

### LINKED ISSUE #2286: Validate user provided Histogram bounds at sdk during Instrument creation time
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/meter.rs#L385 is only validating name,unit etc. We should validate the buckets at this point, and if validation fails, we should either
1. Return no-op instrument as do when other validation fails.
2. Use default bounds, and ignore the user-provided one.

Emit WARN internal log in either case.

### PR DESCRIPTION
**Pull request by cijothomas**
Fixes #2286

### CODE REVIEW

**Review by lalitb — APPROVED** [review]

File: opentelemetry-sdk/src/metrics/meter.rs [hunk 1]
```diff
@@ -533,6 +550,25 @@ fn validate_instrument_config(name: &str, unit: &Option<Cow<'static, str>>) -> M
     validate_instrument_name(name).and_then(|_| validate_instrument_unit(unit))
 }
 
+fn validate_buckets(buckets: &[f64]) -> MetricResult<()> {
+    if buckets.is_empty() {
+        return Err(MetricError::InvalidInstrumentConfiguration(
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/meter.rs:555]: We should allow empty buckets for histogram, right?

File: opentelemetry-sdk/src/metrics/meter.rs [hunk 2]
```diff
@@ -533,6 +550,25 @@ fn validate_instrument_config(name: &str, unit: &Option<Cow<'static, str>>) -> M
...
+            "Buckets must not be empty",
+        ));
+    }
+
+    // validate that buckets are sorted and non-duplicate
+    for window in buckets.windows(2) {
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/meter.rs:561]: I think it's more readable (also a bit more efficient) to use a simple `for` loop here.

```rust
if let Some(boundaries) = builder.boundaries {
    for i in 1..boundaries.len() {
        if boundaries[i] <= boundaries[i - 1] {
            return Err(MetricError::InvalidInstrumentConfiguration(
                "Buckets must be sorted and non-duplicate",
            ));
        }
    }
}
```

File: opentelemetry-sdk/src/metrics/meter.rs [hunk 3]
```diff
@@ -533,6 +550,25 @@ fn validate_instrument_config(name: &str, unit: &Option<Cow<'static, str>>) -> M
     validate_instrument_name(name).and_then(|_| validate_instrument_unit(unit))
 }
 
+fn validate_buckets(buckets: &[f64]) -> MetricResult<()> {
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/meter.rs:553]: We should check for `f64::NAN`, `f64::INFINITY`, and `f64::NEG_INFINITY` as well.

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 4]
```diff
@@ -178,6 +178,27 @@ mod tests {
...
+            let test_context = TestContext::new(Temporality::Cumulative);
+            let histogram = test_context
+                .meter()
+                .f64_histogram("test")
+                .with_boundaries(buckets)
+                .build();
+            histogram.record(1.9, &[]);
+            test_context.flush_metrics();
+
+            // As buckets via Advisory params are invalid, no metrics should be
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/mod.rs:198]:
```suggestion
            // As buckets provided via Advisory params are invalid, no metrics should be
```

File: opentelemetry-sdk/src/metrics/meter.rs [hunk 5]
```diff
@@ -394,6 +394,23 @@ impl SdkMeter {
             return Histogram::new(Arc::new(NoopSyncInstrument::new()));
         }
 
+        if let Some(ref boundaries) = builder.boundaries {
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/meter.rs:397]: Let's remove the validation checks from the `Histogram` struct now that we would be checking it during instrument creation.

https://github.com/open-telemetry/opentelemetry-rust/blob/8e6b479684d550fb70b570d059080488b893aaf4/opentelemetry-sdk/src/metrics/internal/histogram.rs#L78-L79

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 6]
```diff
@@ -178,6 +178,29 @@ mod tests {
             // As instrument name is invalid, no metrics should be exported
             test_context.check_no_metrics();
         }
+
+        let invalid_bucket_boundaries = vec![
+            vec![1.0, 1.0],                          // duplicate boundaries
+            vec![1.0, 2.0, 3.0, 2.0],                // duplicate non consequent boundaries
+            vec![1.0, 2.0, 3.0, 4.0, 2.5],           // unsorted boundaries
+            vec![1.0, 2.0, 3.0, f64::INFINITY, 4.0], // boundaries with NaNs
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/mod.rs:186]:
```suggestion
            vec![1.0, 2.0, 3.0, f64::INFINITY, 4.0], // boundaries with positive infinity
```

File: opentelemetry-sdk/src/metrics/mod.rs [hunk 7]
```diff
@@ -178,6 +178,29 @@ mod tests {
...
+            vec![1.0, 2.0, 3.0, f64::NAN],           // boundaries with NaNs
+            vec![f64::NEG_INFINITY, 2.0, 3.0],       // boundaries with NaNs
```
Comment (utpilla) [inline opentelemetry-sdk/src/metrics/mod.rs:188]:
```suggestion
            vec![f64::NEG_INFINITY, 2.0, 3.0],       // boundaries with negative infinity
```

File: opentelemetry-sdk/src/metrics/meter.rs (hunk 5 above)
Comment (cijothomas) [reply opentelemetry-sdk/src/metrics/meter.rs:397]: The view route is unvalidated still I think. Something we need to comeback to and fix.

Comment (utpilla) [reply opentelemetry-sdk/src/metrics/meter.rs:397]: Ah yes.

**Review by utpilla — APPROVED** [review]

File: opentelemetry/src/metrics/instruments/mod.rs [hunk 8]
```diff
@@ -87,7 +87,26 @@ impl<'a, T> HistogramBuilder<'a, T> {
...
+    /// # Notes
+    /// - Boundaries must not contain `f64::NAN`, `f64::INFINITY` or
+    ///   `f64::NEG_INFINITY`
+    /// - Values must be in strictly increasing order (e.g., each value must be
+    ///   greater than the previous).
+    /// - Boundaries must not contain duplicate values.
+    ///
+    /// If invalid boundaries are provided, the instrument will not report
+    /// measurements.
+    /// Providing an empty `vec![]` means no bucket information will be
```
Comment (utpilla) [inline opentelemetry/src/metrics/instruments/mod.rs:102]: With the current implementation, we would still count and export the bucket information. It would just be one bucket though. We should probably change the implementation to avoid bucket counting altogether in case of empty bounds.

Comment (cijothomas) [reply opentelemetry/src/metrics/instruments/mod.rs:102]: https://github.com/open-telemetry/opentelemetry-rust/issues/2354
