### PR TITLE
fix(sdk, zipkin, otlp): use `temp_env` for testing

### LINKED ISSUE #1383: Consider `temp-env`  for environment testing
> I moved common code for http and tonic exporters in `exporter/mod.rs` (function to parse header from string and test helper to run tests with isolated env variables)
I wanted to minimize the changes but maybe it should be a good idea to use a crate like https://crates.io/crates/temp-env for environment related testing

_Originally posted by @harscoet in https://github.com/open-telemetry/opentelemetry-rust/pull/1377_

### PR DESCRIPTION
**Pull request by TommyCpp**
Fixes #1383
Design discussion issue (if applicable) #

## Changes

Replace all env locks with `temp-env` create

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by jtescher — APPROVED** [review]

**Review by lalitb — APPROVED** [review]

File: opentelemetry-sdk/src/metrics/meter_provider.rs [hunk 1]
```diff
@@ -247,51 +247,54 @@ mod tests {
             .build();
         assert_service_name(custom_meter_provider, Some("test_service"));
 
-        // If `OTEL_RESOURCE_ATTRIBUTES` is set, read them automatically
```
Comment (hdost) [inline opentelemetry-sdk/src/metrics/meter_provider.rs:250]: OPT:Do we want to remove this comment?

**Review by hdost — APPROVED** [review]
Excellent!
